export const iranianCity = [
    {
      province: "مرکزی",
      value: "آشتیان",
      label: "آشتیان",
      id: 2,
    },
    {
      province: "مرکزی",
      value: "اراک",
      label: "اراک",
      id: 1,
    },
    {
      province: "مرکزی",
      value: "تفرش",
      label: "تفرش",
      id: 3,
    },
    {
      province: "مرکزی",
      value: "خمين",
      label: "خمين",
      id: 4,
    },
    {
      province: "مرکزی",
      value: "خنداب",
      label: "خنداب",
      id: 12,
    },
    {
      province: "مرکزی",
      value: "دليجان",
      label: "دليجان",
      id: 5,
    },
    {
      province: "مرکزی",
      value: "زرنديه",
      label: "زرنديه",
      id: 10,
    },
    {
      province: "مرکزی",
      value: "ساوه",
      label: "ساوه",
      id: 6,
    },
    {
      province: "مرکزی",
      value: "شازند",
      label: "شازند",
      id: 7,
    },
    {
      province: "مرکزی",
      value: "فراهان",
      label: "فراهان",
      id: 13,
    },
    {
      province: "مرکزی",
      value: "محلات",
      label: "محلات",
      id: 9,
    },
    {
      province: "مرکزی",
      value: "کميجان",
      label: "کميجان",
      id: 11,
    },
    {
      province: "گیلان",
      value: "آستارا",
      label: "آستارا",
      id: 1,
    },
    {
      province: "گیلان",
      value: "آستانه اشرفيه",
      label: "آستانه اشرفيه",
      id: 2,
    },
    {
      province: "گیلان",
      value: "املش",
      label: "املش",
      id: 13,
    },
    {
      province: "گیلان",
      value: "بندرانزلي",
      label: "بندرانزلي",
      id: 3,
    },
    {
      province: "گیلان",
      value: "خمام",
      label: "خمام",
      id: 17,
    },
    {
      province: "گیلان",
      value: "رشت",
      label: "رشت",
      id: 5,
    },
    {
      province: "گیلان",
      value: "رضوانشهر",
      label: "رضوانشهر",
      id: 14,
    },
    {
      province: "گیلان",
      value: "رودبار",
      label: "رودبار",
      id: 6,
    },
    {
      province: "گیلان",
      value: "رودسر",
      label: "رودسر",
      id: 7,
    },
    {
      province: "گیلان",
      value: "سياهكل",
      label: "سياهكل",
      id: 15,
    },
    {
      province: "گیلان",
      value: "شفت",
      label: "شفت",
      id: 12,
    },
    {
      province: "گیلان",
      value: "صومعه سرا",
      label: "صومعه سرا",
      id: 8,
    },
    {
      province: "گیلان",
      value: "طوالش",
      label: "طوالش",
      id: 4,
    },
    {
      province: "گیلان",
      value: "فومن",
      label: "فومن",
      id: 9,
    },
    {
      province: "گیلان",
      value: "لاهيجان",
      label: "لاهيجان",
      id: 11,
    },
    {
      province: "گیلان",
      value: "لنگرود",
      label: "لنگرود",
      id: 10,
    },
    {
      province: "گیلان",
      value: "ماسال",
      label: "ماسال",
      id: 16,
    },
    {
      province: "مازندران",
      value: "آمل",
      label: "آمل",
      id: 1,
    },
    {
      province: "مازندران",
      value: "بابل",
      label: "بابل",
      id: 2,
    },
    {
      province: "مازندران",
      value: "بابلسر",
      label: "بابلسر",
      id: 16,
    },
    {
      province: "مازندران",
      value: "بهشهر",
      label: "بهشهر",
      id: 4,
    },
    {
      province: "مازندران",
      value: "تنكابن",
      label: "تنكابن",
      id: 5,
    },
    {
      province: "مازندران",
      value: "جويبار",
      label: "جويبار",
      id: 21,
    },
    {
      province: "مازندران",
      value: "رامسر",
      label: "رامسر",
      id: 6,
    },
    {
      province: "مازندران",
      value: "سارئ",
      label: "سارئ",
      id: 7,
    },
    {
      province: "مازندران",
      value: "سوادكوه",
      label: "سوادكوه",
      id: 8,
    },
    {
      province: "مازندران",
      value: "سوادکوه شمالي",
      label: "سوادکوه شمالي",
      id: 27,
    },
    {
      province: "مازندران",
      value: "سيمرغ",
      label: "سيمرغ",
      id: 26,
    },
    {
      province: "مازندران",
      value: "عباس آباد",
      label: "عباس آباد",
      id: 24,
    },
    {
      province: "مازندران",
      value: "فريدونكنار",
      label: "فريدونكنار",
      id: 23,
    },
    {
      province: "مازندران",
      value: "قائم شهر",
      label: "قائم شهر",
      id: 10,
    },
    {
      province: "مازندران",
      value: "محمودآباد",
      label: "محمودآباد",
      id: 18,
    },
    {
      province: "مازندران",
      value: "مياندورود",
      label: "مياندورود",
      id: 25,
    },
    {
      province: "مازندران",
      value: "نكا",
      label: "نكا",
      id: 19,
    },
    {
      province: "مازندران",
      value: "نور",
      label: "نور",
      id: 14,
    },
    {
      province: "مازندران",
      value: "نوشهر",
      label: "نوشهر",
      id: 15,
    },
    {
      province: "مازندران",
      value: "چالوس",
      label: "چالوس",
      id: 20,
    },
    {
      province: "مازندران",
      value: "کلاردشت",
      label: "کلاردشت",
      id: 28,
    },
    {
      province: "مازندران",
      value: "گلوگاه",
      label: "گلوگاه",
      id: 22,
    },
    {
      province: "آذربایجان شرقی",
      value: "آذرشهر",
      label: "آذرشهر",
      id: 21,
    },
    {
      province: "آذربایجان شرقی",
      value: "اسکو",
      label: "اسکو",
      id: 22,
    },
    {
      province: "آذربایجان شرقی",
      value: "اهر",
      label: "اهر",
      id: 2,
    },
    {
      province: "آذربایجان شرقی",
      value: "بستان آباد",
      label: "بستان آباد",
      id: 13,
    },
    {
      province: "آذربایجان شرقی",
      value: "بناب",
      label: "بناب",
      id: 12,
    },
    {
      province: "آذربایجان شرقی",
      value: "تبريز",
      label: "تبريز",
      id: 3,
    },
    {
      province: "آذربایجان شرقی",
      value: "جلفا",
      label: "جلفا",
      id: 19,
    },
    {
      province: "آذربایجان شرقی",
      value: "خداآفرين",
      label: "خداآفرين",
      id: 26,
    },
    {
      province: "آذربایجان شرقی",
      value: "سراب",
      label: "سراب",
      id: 5,
    },
    {
      province: "آذربایجان شرقی",
      value: "شبستر",
      label: "شبستر",
      id: 14,
    },
    {
      province: "آذربایجان شرقی",
      value: "عجب شير",
      label: "عجب شير",
      id: 25,
    },
    {
      province: "آذربایجان شرقی",
      value: "مراغه",
      label: "مراغه",
      id: 6,
    },
    {
      province: "آذربایجان شرقی",
      value: "مرند",
      label: "مرند",
      id: 7,
    },
    {
      province: "آذربایجان شرقی",
      value: "ملکان",
      label: "ملکان",
      id: 20,
    },
    {
      province: "آذربایجان شرقی",
      value: "ميانه",
      label: "ميانه",
      id: 10,
    },
    {
      province: "آذربایجان شرقی",
      value: "هريس",
      label: "هريس",
      id: 16,
    },
    {
      province: "آذربایجان شرقی",
      value: "هشترود",
      label: "هشترود",
      id: 11,
    },
    {
      province: "آذربایجان شرقی",
      value: "هوراند",
      label: "هوراند",
      id: 27,
    },
    {
      province: "آذربایجان شرقی",
      value: "ورزقان",
      label: "ورزقان",
      id: 24,
    },
    {
      province: "آذربایجان شرقی",
      value: "چاراويماق",
      label: "چاراويماق",
      id: 23,
    },
    {
      province: "آذربایجان شرقی",
      value: "کليبر",
      label: "کليبر",
      id: 15,
    },
    {
      province: "آذربایجان غربی",
      value: "اروميه",
      label: "اروميه",
      id: 1,
    },
    {
      province: "آذربایجان غربی",
      value: "اشنويه",
      label: "اشنويه",
      id: 13,
    },
    {
      province: "آذربایجان غربی",
      value: "باروق",
      label: "باروق",
      id: 19,
    },
    {
      province: "آذربایجان غربی",
      value: "بوكان",
      label: "بوكان",
      id: 10,
    },
    {
      province: "آذربایجان غربی",
      value: "تكاب",
      label: "تكاب",
      id: 12,
    },
    {
      province: "آذربایجان غربی",
      value: "خوئ",
      label: "خوئ",
      id: 3,
    },
    {
      province: "آذربایجان غربی",
      value: "سردشت",
      label: "سردشت",
      id: 4,
    },
    {
      province: "آذربایجان غربی",
      value: "سلماس",
      label: "سلماس",
      id: 5,
    },
    {
      province: "آذربایجان غربی",
      value: "شاهين دژ",
      label: "شاهين دژ",
      id: 11,
    },
    {
      province: "آذربایجان غربی",
      value: "شوط",
      label: "شوط",
      id: 17,
    },
    {
      province: "آذربایجان غربی",
      value: "ماكو",
      label: "ماكو",
      id: 6,
    },
    {
      province: "آذربایجان غربی",
      value: "مهاباد",
      label: "مهاباد",
      id: 7,
    },
    {
      province: "آذربایجان غربی",
      value: "مياندوآب",
      label: "مياندوآب",
      id: 8,
    },
    {
      province: "آذربایجان غربی",
      value: "ميرآباد",
      label: "ميرآباد",
      id: 20,
    },
    {
      province: "آذربایجان غربی",
      value: "نقده",
      label: "نقده",
      id: 9,
    },
    {
      province: "آذربایجان غربی",
      value: "پلدشت",
      label: "پلدشت",
      id: 15,
    },
    {
      province: "آذربایجان غربی",
      value: "پيرانشهر",
      label: "پيرانشهر",
      id: 2,
    },
    {
      province: "آذربایجان غربی",
      value: "چالدران",
      label: "چالدران",
      id: 14,
    },
    {
      province: "آذربایجان غربی",
      value: "چايپاره",
      label: "چايپاره",
      id: 16,
    },
    {
      province: "آذربایجان غربی",
      value: "چهاربرج",
      label: "چهاربرج",
      id: 18,
    },
    {
      province: "کرمانشاه",
      value: "اسلام آبادغرب",
      label: "اسلام آبادغرب",
      id: 1,
    },
    {
      province: "کرمانشاه",
      value: "ثلاث باباجاني",
      label: "ثلاث باباجاني",
      id: 12,
    },
    {
      province: "کرمانشاه",
      value: "جوانرود",
      label: "جوانرود",
      id: 9,
    },
    {
      province: "کرمانشاه",
      value: "دالاهو",
      label: "دالاهو",
      id: 13,
    },
    {
      province: "کرمانشاه",
      value: "روانسر",
      label: "روانسر",
      id: 14,
    },
    {
      province: "کرمانشاه",
      value: "سرپل ذهاب",
      label: "سرپل ذهاب",
      id: 4,
    },
    {
      province: "کرمانشاه",
      value: "سنقر",
      label: "سنقر",
      id: 5,
    },
    {
      province: "کرمانشاه",
      value: "صحنه",
      label: "صحنه",
      id: 10,
    },
    {
      province: "کرمانشاه",
      value: "قصرشيرين",
      label: "قصرشيرين",
      id: 6,
    },
    {
      province: "کرمانشاه",
      value: "هرسين",
      label: "هرسين",
      id: 11,
    },
    {
      province: "کرمانشاه",
      value: "پاوه",
      label: "پاوه",
      id: 3,
    },
    {
      province: "کرمانشاه",
      value: "کرمانشاه",
      label: "کرمانشاه",
      id: 2,
    },
    {
      province: "کرمانشاه",
      value: "کنگاور",
      label: "کنگاور",
      id: 7,
    },
    {
      province: "کرمانشاه",
      value: "گیلانغرب",
      label: "گیلانغرب",
      id: 8,
    },
    {
      province: "خوزستان",
      value: "آبادان",
      label: "آبادان",
      id: 1,
    },
    {
      province: "خوزستان",
      value: "آغاجاري",
      label: "آغاجاري",
      id: 26,
    },
    {
      province: "خوزستان",
      value: "اميديه",
      label: "اميديه",
      id: 16,
    },
    {
      province: "خوزستان",
      value: "انديمشک",
      label: "انديمشک",
      id: 2,
    },
    {
      province: "خوزستان",
      value: "انديکا",
      label: "انديکا",
      id: 21,
    },
    {
      province: "خوزستان",
      value: "اهواز",
      label: "اهواز",
      id: 3,
    },
    {
      province: "خوزستان",
      value: "ايذه",
      label: "ايذه",
      id: 4,
    },
    {
      province: "خوزستان",
      value: "باغ ملک",
      label: "باغ ملک",
      id: 15,
    },
    {
      province: "خوزستان",
      value: "باوي",
      label: "باوي",
      id: 24,
    },
    {
      province: "خوزستان",
      value: "بندرماهشهر",
      label: "بندرماهشهر",
      id: 5,
    },
    {
      province: "خوزستان",
      value: "بهبهان",
      label: "بهبهان",
      id: 6,
    },
    {
      province: "خوزستان",
      value: "حميديه",
      label: "حميديه",
      id: 25,
    },
    {
      province: "خوزستان",
      value: "خرمشهر",
      label: "خرمشهر",
      id: 7,
    },
    {
      province: "خوزستان",
      value: "دزفول",
      label: "دزفول",
      id: 8,
    },
    {
      province: "خوزستان",
      value: "دزپارت",
      label: "دزپارت",
      id: 29,
    },
    {
      province: "خوزستان",
      value: "دشت آزادگان",
      label: "دشت آزادگان",
      id: 9,
    },
    {
      province: "خوزستان",
      value: "رامشير",
      label: "رامشير",
      id: 19,
    },
    {
      province: "خوزستان",
      value: "رامهرمز",
      label: "رامهرمز",
      id: 10,
    },
    {
      province: "خوزستان",
      value: "شادگان",
      label: "شادگان",
      id: 11,
    },
    {
      province: "خوزستان",
      value: "شوش",
      label: "شوش",
      id: 14,
    },
    {
      province: "خوزستان",
      value: "شوشتر",
      label: "شوشتر",
      id: 12,
    },
    {
      province: "خوزستان",
      value: "لالي",
      label: "لالي",
      id: 17,
    },
    {
      province: "خوزستان",
      value: "مسجدسليمان",
      label: "مسجدسليمان",
      id: 13,
    },
    {
      province: "خوزستان",
      value: "هفتکل",
      label: "هفتکل",
      id: 22,
    },
    {
      province: "خوزستان",
      value: "هنديجان",
      label: "هنديجان",
      id: 18,
    },
    {
      province: "خوزستان",
      value: "هويزه",
      label: "هويزه",
      id: 23,
    },
    {
      province: "خوزستان",
      value: "کارون",
      label: "کارون",
      id: 27,
    },
    {
      province: "خوزستان",
      value: "کرخه",
      label: "کرخه",
      id: 28,
    },
    {
      province: "خوزستان",
      value: "گتوند",
      label: "گتوند",
      id: 20,
    },
    {
      province: "فارس",
      value: "آباده",
      label: "آباده",
      id: 1,
    },
    {
      province: "فارس",
      value: "ارسنجان",
      label: "ارسنجان",
      id: 17,
    },
    {
      province: "فارس",
      value: "استهبان",
      label: "استهبان",
      id: 2,
    },
    {
      province: "فارس",
      value: "اقليد",
      label: "اقليد",
      id: 3,
    },
    {
      province: "فارس",
      value: "اوز",
      label: "اوز",
      id: 36,
    },
    {
      province: "فارس",
      value: "بختگان",
      label: "بختگان",
      id: 35,
    },
    {
      province: "فارس",
      value: "بوانات",
      label: "بوانات",
      id: 16,
    },
    {
      province: "فارس",
      value: "بيضا",
      label: "بيضا",
      id: 31,
    },
    {
      province: "فارس",
      value: "جهرم",
      label: "جهرم",
      id: 4,
    },
    {
      province: "فارس",
      value: "جويم",
      label: "جويم",
      id: 37,
    },
    {
      province: "فارس",
      value: "خرامه",
      label: "خرامه",
      id: 29,
    },
    {
      province: "فارس",
      value: "خرم بيد",
      label: "خرم بيد",
      id: 18,
    },
    {
      province: "فارس",
      value: "خفر",
      label: "خفر",
      id: 34,
    },
    {
      province: "فارس",
      value: "خنج",
      label: "خنج",
      id: 24,
    },
    {
      province: "فارس",
      value: "داراب",
      label: "داراب",
      id: 5,
    },
    {
      province: "فارس",
      value: "رستم",
      label: "رستم",
      id: 26,
    },
    {
      province: "فارس",
      value: "زرقان",
      label: "زرقان",
      id: 30,
    },
    {
      province: "فارس",
      value: "زرين دشت",
      label: "زرين دشت",
      id: 19,
    },
    {
      province: "فارس",
      value: "سروستان",
      label: "سروستان",
      id: 25,
    },
    {
      province: "فارس",
      value: "سرچهان",
      label: "سرچهان",
      id: 32,
    },
    {
      province: "فارس",
      value: "سپيدان",
      label: "سپيدان",
      id: 6,
    },
    {
      province: "فارس",
      value: "شيراز",
      label: "شيراز",
      id: 7,
    },
    {
      province: "فارس",
      value: "فراشبند",
      label: "فراشبند",
      id: 22,
    },
    {
      province: "فارس",
      value: "فسا",
      label: "فسا",
      id: 8,
    },
    {
      province: "فارس",
      value: "فيروزآباد",
      label: "فيروزآباد",
      id: 9,
    },
    {
      province: "فارس",
      value: "قيروکارزين",
      label: "قيروکارزين",
      id: 20,
    },
    {
      province: "فارس",
      value: "لارستان",
      label: "لارستان",
      id: 11,
    },
    {
      province: "فارس",
      value: "لامرد",
      label: "لامرد",
      id: 15,
    },
    {
      province: "فارس",
      value: "مرودشت",
      label: "مرودشت",
      id: 12,
    },
    {
      province: "فارس",
      value: "ممسني",
      label: "ممسني",
      id: 13,
    },
    {
      province: "فارس",
      value: "مهر",
      label: "مهر",
      id: 21,
    },
    {
      province: "فارس",
      value: "ني ريز",
      label: "ني ريز",
      id: 14,
    },
    {
      province: "فارس",
      value: "پاسارگاد",
      label: "پاسارگاد",
      id: 23,
    },
    {
      province: "فارس",
      value: "کازرون",
      label: "کازرون",
      id: 10,
    },
    {
      province: "فارس",
      value: "کوار",
      label: "کوار",
      id: 28,
    },
    {
      province: "فارس",
      value: "کوه چنار",
      label: "کوه چنار",
      id: 33,
    },
    {
      province: "فارس",
      value: "گراش",
      label: "گراش",
      id: 27,
    },
    {
      province: "کرمان",
      value: "ارزوئيه",
      label: "ارزوئيه",
      id: 23,
    },
    {
      province: "کرمان",
      value: "انار",
      label: "انار",
      id: 20,
    },
    {
      province: "کرمان",
      value: "بافت",
      label: "بافت",
      id: 1,
    },
    {
      province: "کرمان",
      value: "بردسير",
      label: "بردسير",
      id: 10,
    },
    {
      province: "کرمان",
      value: "بم",
      label: "بم",
      id: 2,
    },
    {
      province: "کرمان",
      value: "جيرفت",
      label: "جيرفت",
      id: 3,
    },
    {
      province: "کرمان",
      value: "رابر",
      label: "رابر",
      id: 18,
    },
    {
      province: "کرمان",
      value: "راور",
      label: "راور",
      id: 11,
    },
    {
      province: "کرمان",
      value: "رفسنجان",
      label: "رفسنجان",
      id: 4,
    },
    {
      province: "کرمان",
      value: "رودبارجنوب",
      label: "رودبارجنوب",
      id: 15,
    },
    {
      province: "کرمان",
      value: "ريگان",
      label: "ريگان",
      id: 17,
    },
    {
      province: "کرمان",
      value: "زرند",
      label: "زرند",
      id: 5,
    },
    {
      province: "کرمان",
      value: "سيرجان",
      label: "سيرجان",
      id: 6,
    },
    {
      province: "کرمان",
      value: "شهربابك",
      label: "شهربابك",
      id: 7,
    },
    {
      province: "کرمان",
      value: "عنبرآباد",
      label: "عنبرآباد",
      id: 12,
    },
    {
      province: "کرمان",
      value: "فارياب",
      label: "فارياب",
      id: 22,
    },
    {
      province: "کرمان",
      value: "فهرج",
      label: "فهرج",
      id: 19,
    },
    {
      province: "کرمان",
      value: "قلعه گنج",
      label: "قلعه گنج",
      id: 16,
    },
    {
      province: "کرمان",
      value: "کرمان",
      label: "کرمان",
      id: 8,
    },
    {
      province: "کرمان",
      value: "كهنوج",
      label: "كهنوج",
      id: 9,
    },
    {
      province: "کرمان",
      value: "كوهبنان",
      label: "كوهبنان",
      id: 14,
    },
    {
      province: "کرمان",
      value: "منوجان",
      label: "منوجان",
      id: 13,
    },
    {
      province: "کرمان",
      value: "نرماشير",
      label: "نرماشير",
      id: 21,
    },
    {
      province: "خراسان رضوی",
      value: "باخرز",
      label: "باخرز",
      id: 37,
    },
    {
      province: "خراسان رضوی",
      value: "بجستان",
      label: "بجستان",
      id: 31,
    },
    {
      province: "خراسان رضوی",
      value: "بردسكن",
      label: "بردسكن",
      id: 23,
    },
    {
      province: "خراسان رضوی",
      value: "تايباد",
      label: "تايباد",
      id: 4,
    },
    {
      province: "خراسان رضوی",
      value: "تربت جام",
      label: "تربت جام",
      id: 6,
    },
    {
      province: "خراسان رضوی",
      value: "تربت حيدريه",
      label: "تربت حيدريه",
      id: 5,
    },
    {
      province: "خراسان رضوی",
      value: "جغتاي",
      label: "جغتاي",
      id: 34,
    },
    {
      province: "خراسان رضوی",
      value: "جوين",
      label: "جوين",
      id: 36,
    },
    {
      province: "خراسان رضوی",
      value: "خليل آباد",
      label: "خليل آباد",
      id: 29,
    },
    {
      province: "خراسان رضوی",
      value: "خواف",
      label: "خواف",
      id: 19,
    },
    {
      province: "خراسان رضوی",
      value: "خوشاب",
      label: "خوشاب",
      id: 38,
    },
    {
      province: "خراسان رضوی",
      value: "داورزن",
      label: "داورزن",
      id: 39,
    },
    {
      province: "خراسان رضوی",
      value: "درگز",
      label: "درگز",
      id: 7,
    },
    {
      province: "خراسان رضوی",
      value: "رشتخوار",
      label: "رشتخوار",
      id: 27,
    },
    {
      province: "خراسان رضوی",
      value: "زاوه",
      label: "زاوه",
      id: 35,
    },
    {
      province: "خراسان رضوی",
      value: "زبرخان",
      label: "زبرخان",
      id: 42,
    },
    {
      province: "خراسان رضوی",
      value: "سبزوار",
      label: "سبزوار",
      id: 8,
    },
    {
      province: "خراسان رضوی",
      value: "سرخس",
      label: "سرخس",
      id: 20,
    },
    {
      province: "خراسان رضوی",
      value: "ششتمد",
      label: "ششتمد",
      id: 43,
    },
    {
      province: "خراسان رضوی",
      value: "صالح آباد",
      label: "صالح آباد",
      id: 40,
    },
    {
      province: "خراسان رضوی",
      value: "طرقبه شانديز",
      label: "طرقبه شانديز",
      id: 32,
    },
    {
      province: "خراسان رضوی",
      value: "فريمان",
      label: "فريمان",
      id: 22,
    },
    {
      province: "خراسان رضوی",
      value: "فيروزه",
      label: "فيروزه",
      id: 33,
    },
    {
      province: "خراسان رضوی",
      value: "قوچان",
      label: "قوچان",
      id: 13,
    },
    {
      province: "خراسان رضوی",
      value: "كاشمر",
      label: "كاشمر",
      id: 14,
    },
    {
      province: "خراسان رضوی",
      value: "كلات",
      label: "كلات",
      id: 28,
    },
    {
      province: "خراسان رضوی",
      value: "مشهد",
      label: "مشهد",
      id: 16,
    },
    {
      province: "خراسان رضوی",
      value: "مه ولات",
      label: "مه ولات",
      id: 30,
    },
    {
      province: "خراسان رضوی",
      value: "ميان جلگه",
      label: "ميان جلگه",
      id: 45,
    },
    {
      province: "خراسان رضوی",
      value: "نيشابور",
      label: "نيشابور",
      id: 17,
    },
    {
      province: "خراسان رضوی",
      value: "چناران",
      label: "چناران",
      id: 18,
    },
    {
      province: "خراسان رضوی",
      value: "کوهسرخ",
      label: "کوهسرخ",
      id: 41,
    },
    {
      province: "خراسان رضوی",
      value: "گلبهار",
      label: "گلبهار",
      id: 44,
    },
    {
      province: "خراسان رضوی",
      value: "گناباد",
      label: "گناباد",
      id: 15,
    },
    {
      province: "اصفهان",
      value: "آران وبيدگل",
      label: "آران وبيدگل",
      id: 18,
    },
    {
      province: "اصفهان",
      value: "اردستان",
      label: "اردستان",
      id: 1,
    },
    {
      province: "اصفهان",
      value: "اصفهان",
      label: "اصفهان",
      id: 2,
    },
    {
      province: "اصفهان",
      value: "برخوار",
      label: "برخوار",
      id: 22,
    },
    {
      province: "اصفهان",
      value: "بو يين و مياندشت",
      label: "بو يين و مياندشت",
      id: 24,
    },
    {
      province: "اصفهان",
      value: "تيران وکرون",
      label: "تيران وکرون",
      id: 19,
    },
    {
      province: "اصفهان",
      value: "جرقويه",
      label: "جرقويه",
      id: 26,
    },
    {
      province: "اصفهان",
      value: "خميني شهر",
      label: "خميني شهر",
      id: 3,
    },
    {
      province: "اصفهان",
      value: "خوانسار",
      label: "خوانسار",
      id: 4,
    },
    {
      province: "اصفهان",
      value: "خور و بيابانک",
      label: "خور و بيابانک",
      id: 23,
    },
    {
      province: "اصفهان",
      value: "دهاقان",
      label: "دهاقان",
      id: 21,
    },
    {
      province: "اصفهان",
      value: "سميرم",
      label: "سميرم",
      id: 5,
    },
    {
      province: "اصفهان",
      value: "شاهين شهروميمه",
      label: "شاهين شهروميمه",
      id: 16,
    },
    {
      province: "اصفهان",
      value: "شهرضا",
      label: "شهرضا",
      id: 9,
    },
    {
      province: "اصفهان",
      value: "فريدن",
      label: "فريدن",
      id: 6,
    },
    {
      province: "اصفهان",
      value: "فريدونشهر",
      label: "فريدونشهر",
      id: 7,
    },
    {
      province: "اصفهان",
      value: "فلاورجان",
      label: "فلاورجان",
      id: 8,
    },
    {
      province: "اصفهان",
      value: "لنجان",
      label: "لنجان",
      id: 12,
    },
    {
      province: "اصفهان",
      value: "مبارکه",
      label: "مبارکه",
      id: 17,
    },
    {
      province: "اصفهان",
      value: "نايين",
      label: "نايين",
      id: 13,
    },
    {
      province: "اصفهان",
      value: "نجف آباد",
      label: "نجف آباد",
      id: 14,
    },
    {
      province: "اصفهان",
      value: "نطنز",
      label: "نطنز",
      id: 15,
    },
    {
      province: "اصفهان",
      value: "هرند",
      label: "هرند",
      id: 28,
    },
    {
      province: "اصفهان",
      value: "ورزنه",
      label: "ورزنه",
      id: 27,
    },
    {
      province: "اصفهان",
      value: "چادگان",
      label: "چادگان",
      id: 20,
    },
    {
      province: "اصفهان",
      value: "کاشان",
      label: "کاشان",
      id: 10,
    },
    {
      province: "اصفهان",
      value: "کوهپايه",
      label: "کوهپايه",
      id: 25,
    },
    {
      province: "اصفهان",
      value: "گلپايگان",
      label: "گلپايگان",
      id: 11,
    },
    {
      province: "سیستان و بلوچستان",
      value: "ايرانشهر",
      label: "ايرانشهر",
      id: 1,
    },
    {
      province: "سیستان و بلوچستان",
      value: "بمپور",
      label: "بمپور",
      id: 20,
    },
    {
      province: "سیستان و بلوچستان",
      value: "تفتان",
      label: "تفتان",
      id: 21,
    },
    {
      province: "سیستان و بلوچستان",
      value: "خاش",
      label: "خاش",
      id: 3,
    },
    {
      province: "سیستان و بلوچستان",
      value: "دشتياري",
      label: "دشتياري",
      id: 22,
    },
    {
      province: "سیستان و بلوچستان",
      value: "دلگان",
      label: "دلگان",
      id: 12,
    },
    {
      province: "سیستان و بلوچستان",
      value: "راسک",
      label: "راسک",
      id: 8,
    },
    {
      province: "سیستان و بلوچستان",
      value: "زابل",
      label: "زابل",
      id: 4,
    },
    {
      province: "سیستان و بلوچستان",
      value: "زاهدان",
      label: "زاهدان",
      id: 5,
    },
    {
      province: "سیستان و بلوچستان",
      value: "زرآباد",
      label: "زرآباد",
      id: 26,
    },
    {
      province: "سیستان و بلوچستان",
      value: "زهک",
      label: "زهک",
      id: 10,
    },
    {
      province: "سیستان و بلوچستان",
      value: "سراوان",
      label: "سراوان",
      id: 6,
    },
    {
      province: "سیستان و بلوچستان",
      value: "سرباز",
      label: "سرباز",
      id: 23,
    },
    {
      province: "سیستان و بلوچستان",
      value: "سيب و سوران",
      label: "سيب و سوران",
      id: 14,
    },
    {
      province: "سیستان و بلوچستان",
      value: "فنوج",
      label: "فنوج",
      id: 19,
    },
    {
      province: "سیستان و بلوچستان",
      value: "قصرقند",
      label: "قصرقند",
      id: 18,
    },
    {
      province: "سیستان و بلوچستان",
      value: "لاشار",
      label: "لاشار",
      id: 25,
    },
    {
      province: "سیستان و بلوچستان",
      value: "مهرستان",
      label: "مهرستان",
      id: 13,
    },
    {
      province: "سیستان و بلوچستان",
      value: "ميرجاوه",
      label: "ميرجاوه",
      id: 17,
    },
    {
      province: "سیستان و بلوچستان",
      value: "نيمروز",
      label: "نيمروز",
      id: 15,
    },
    {
      province: "سیستان و بلوچستان",
      value: "نيک شهر",
      label: "نيک شهر",
      id: 7,
    },
    {
      province: "سیستان و بلوچستان",
      value: "هامون",
      label: "هامون",
      id: 16,
    },
    {
      province: "سیستان و بلوچستان",
      value: "هيرمند",
      label: "هيرمند",
      id: 11,
    },
    {
      province: "سیستان و بلوچستان",
      value: "چاه بهار",
      label: "چاه بهار",
      id: 2,
    },
    {
      province: "سیستان و بلوچستان",
      value: "کنارک",
      label: "کنارک",
      id: 9,
    },
    {
      province: "سیستان و بلوچستان",
      value: "گلشن",
      label: "گلشن",
      id: 24,
    },
    {
      province: "کردستان",
      value: "بانه",
      label: "بانه",
      id: 1,
    },
    {
      province: "کردستان",
      value: "بيجار",
      label: "بيجار",
      id: 2,
    },
    {
      province: "کردستان",
      value: "دهگلان",
      label: "دهگلان",
      id: 10,
    },
    {
      province: "کردستان",
      value: "ديواندره",
      label: "ديواندره",
      id: 7,
    },
    {
      province: "کردستان",
      value: "سروآباد",
      label: "سروآباد",
      id: 9,
    },
    {
      province: "کردستان",
      value: "سقز",
      label: "سقز",
      id: 3,
    },
    {
      province: "کردستان",
      value: "سنندج",
      label: "سنندج",
      id: 4,
    },
    {
      province: "کردستان",
      value: "قروه",
      label: "قروه",
      id: 5,
    },
    {
      province: "کردستان",
      value: "كامياران",
      label: "كامياران",
      id: 8,
    },
    {
      province: "کردستان",
      value: "مريوان",
      label: "مريوان",
      id: 6,
    },
    {
      province: "همدان",
      value: "اسدآباد",
      label: "اسدآباد",
      id: 6,
    },
    {
      province: "همدان",
      value: "بهار",
      label: "بهار",
      id: 7,
    },
    {
      province: "همدان",
      value: "تويسركان",
      label: "تويسركان",
      id: 1,
    },
    {
      province: "همدان",
      value: "درگزين",
      label: "درگزين",
      id: 10,
    },
    {
      province: "همدان",
      value: "رزن",
      label: "رزن",
      id: 8,
    },
    {
      province: "همدان",
      value: "فامنين",
      label: "فامنين",
      id: 9,
    },
    {
      province: "همدان",
      value: "كبودرآهنگ",
      label: "كبودرآهنگ",
      id: 5,
    },
    {
      province: "همدان",
      value: "ملاير",
      label: "ملاير",
      id: 2,
    },
    {
      province: "همدان",
      value: "نهاوند",
      label: "نهاوند",
      id: 3,
    },
    {
      province: "همدان",
      value: "همدان",
      label: "همدان",
      id: 4,
    },
    {
      province: "چهارمحال و بختیاری",
      value: "اردل",
      label: "اردل",
      id: 5,
    },
    {
      province: "چهارمحال و بختیاری",
      value: "بروجن",
      label: "بروجن",
      id: 1,
    },
    {
      province: "چهارمحال و بختیاری",
      value: "بن",
      label: "بن",
      id: 9,
    },
    {
      province: "چهارمحال و بختیاری",
      value: "خانميرزا",
      label: "خانميرزا",
      id: 10,
    },
    {
      province: "چهارمحال و بختیاری",
      value: "سامان",
      label: "سامان",
      id: 8,
    },
    {
      province: "چهارمحال و بختیاری",
      value: "شهرکرد",
      label: "شهرکرد",
      id: 2,
    },
    {
      province: "چهارمحال و بختیاری",
      value: "فارسان",
      label: "فارسان",
      id: 3,
    },
    {
      province: "چهارمحال و بختیاری",
      value: "فلارد",
      label: "فلارد",
      id: 11,
    },
    {
      province: "چهارمحال و بختیاری",
      value: "لردگان",
      label: "لردگان",
      id: 4,
    },
    {
      province: "چهارمحال و بختیاری",
      value: "کوهرنگ",
      label: "کوهرنگ",
      id: 6,
    },
    {
      province: "چهارمحال و بختیاری",
      value: "کيار",
      label: "کيار",
      id: 7,
    },
    {
      province: "لرستان",
      value: "ازنا",
      label: "ازنا",
      id: 7,
    },
    {
      province: "لرستان",
      value: "اليگودرز",
      label: "اليگودرز",
      id: 1,
    },
    {
      province: "لرستان",
      value: "بروجرد",
      label: "بروجرد",
      id: 2,
    },
    {
      province: "لرستان",
      value: "خرم آباد",
      label: "خرم آباد",
      id: 3,
    },
    {
      province: "لرستان",
      value: "دلفان",
      label: "دلفان",
      id: 4,
    },
    {
      province: "لرستان",
      value: "دورود",
      label: "دورود",
      id: 5,
    },
    {
      province: "لرستان",
      value: "رومشکان",
      label: "رومشکان",
      id: 11,
    },
    {
      province: "لرستان",
      value: "سلسله",
      label: "سلسله",
      id: 9,
    },
    {
      province: "لرستان",
      value: "پلدختر",
      label: "پلدختر",
      id: 8,
    },
    {
      province: "لرستان",
      value: "چگني",
      label: "چگني",
      id: 10,
    },
    {
      province: "لرستان",
      value: "کوهدشت",
      label: "کوهدشت",
      id: 6,
    },
    {
      province: "ایلام",
      value: "آبدانان",
      label: "آبدانان",
      id: 6,
    },
    {
      province: "ایلام",
      value: "ایلام",
      label: "ایلام",
      id: 1,
    },
    {
      province: "ایلام",
      value: "ايوان",
      label: "ايوان",
      id: 7,
    },
    {
      province: "ایلام",
      value: "بدره",
      label: "بدره",
      id: 10,
    },
    {
      province: "ایلام",
      value: "دره شهر",
      label: "دره شهر",
      id: 2,
    },
    {
      province: "ایلام",
      value: "دهلران",
      label: "دهلران",
      id: 3,
    },
    {
      province: "ایلام",
      value: "سيروان",
      label: "سيروان",
      id: 9,
    },
    {
      province: "ایلام",
      value: "ملكشاهي",
      label: "ملكشاهي",
      id: 8,
    },
    {
      province: "ایلام",
      value: "مهران",
      label: "مهران",
      id: 5,
    },
    {
      province: "ایلام",
      value: "هليلان",
      label: "هليلان",
      id: 11,
    },
    {
      province: "ایلام",
      value: "چرداول",
      label: "چرداول",
      id: 4,
    },
    {
      province: "ایلام",
      value: "چوار",
      label: "چوار",
      id: 12,
    },
    {
      province: "کهگیلویه و بویراحمد",
      value: "باشت",
      label: "باشت",
      id: 7,
    },
    {
      province: "کهگیلویه و بویراحمد",
      value: "بهمئي",
      label: "بهمئي",
      id: 5,
    },
    {
      province: "کهگیلویه و بویراحمد",
      value: "بويراحمد",
      label: "بويراحمد",
      id: 1,
    },
    {
      province: "کهگیلویه و بویراحمد",
      value: "دنا",
      label: "دنا",
      id: 4,
    },
    {
      province: "کهگیلویه و بویراحمد",
      value: "كهگيلويه",
      label: "كهگيلويه",
      id: 2,
    },
    {
      province: "کهگیلویه و بویراحمد",
      value: "لنده",
      label: "لنده",
      id: 8,
    },
    {
      province: "کهگیلویه و بویراحمد",
      value: "مارگون",
      label: "مارگون",
      id: 9,
    },
    {
      province: "کهگیلویه و بویراحمد",
      value: "چرام",
      label: "چرام",
      id: 6,
    },
    {
      province: "کهگیلویه و بویراحمد",
      value: "گچساران",
      label: "گچساران",
      id: 3,
    },
    {
      province: "بوشهر",
      value: "بوشهر",
      label: "بوشهر",
      id: 1,
    },
    {
      province: "بوشهر",
      value: "تنگستان",
      label: "تنگستان",
      id: 2,
    },
    {
      province: "بوشهر",
      value: "جم",
      label: "جم",
      id: 9,
    },
    {
      province: "بوشهر",
      value: "دشتستان",
      label: "دشتستان",
      id: 3,
    },
    {
      province: "بوشهر",
      value: "دشتي",
      label: "دشتي",
      id: 4,
    },
    {
      province: "بوشهر",
      value: "دير",
      label: "دير",
      id: 5,
    },
    {
      province: "بوشهر",
      value: "ديلم",
      label: "ديلم",
      id: 8,
    },
    {
      province: "بوشهر",
      value: "عسلويه",
      label: "عسلويه",
      id: 10,
    },
    {
      province: "بوشهر",
      value: "كنگان",
      label: "كنگان",
      id: 6,
    },
    {
      province: "بوشهر",
      value: "گناوه",
      label: "گناوه",
      id: 7,
    },
    {
      province: "زنجان",
      value: "ابهر",
      label: "ابهر",
      id: 1,
    },
    {
      province: "زنجان",
      value: "ايجرود",
      label: "ايجرود",
      id: 6,
    },
    {
      province: "زنجان",
      value: "خدابنده",
      label: "خدابنده",
      id: 3,
    },
    {
      province: "زنجان",
      value: "خرمدره",
      label: "خرمدره",
      id: 7,
    },
    {
      province: "زنجان",
      value: "زنجان",
      label: "زنجان",
      id: 4,
    },
    {
      province: "زنجان",
      value: "سلطانيه",
      label: "سلطانيه",
      id: 10,
    },
    {
      province: "زنجان",
      value: "طارم",
      label: "طارم",
      id: 8,
    },
    {
      province: "زنجان",
      value: "ماهنشان",
      label: "ماهنشان",
      id: 9,
    },
    {
      province: "سمنان",
      value: "آرادان",
      label: "آرادان",
      id: 6,
    },
    {
      province: "سمنان",
      value: "دامغان",
      label: "دامغان",
      id: 1,
    },
    {
      province: "سمنان",
      value: "سرخه",
      label: "سرخه",
      id: 8,
    },
    {
      province: "سمنان",
      value: "سمنان",
      label: "سمنان",
      id: 2,
    },
    {
      province: "سمنان",
      value: "شاهرود",
      label: "شاهرود",
      id: 3,
    },
    {
      province: "سمنان",
      value: "مهدئ شهر",
      label: "مهدئ شهر",
      id: 5,
    },
    {
      province: "سمنان",
      value: "ميامي",
      label: "ميامي",
      id: 7,
    },
    {
      province: "سمنان",
      value: "گرمسار",
      label: "گرمسار",
      id: 4,
    },
    {
      province: "یزد",
      value: "ابركوه",
      label: "ابركوه",
      id: 7,
    },
    {
      province: "یزد",
      value: "اردكان",
      label: "اردكان",
      id: 1,
    },
    {
      province: "یزد",
      value: "اشکذر",
      label: "اشکذر",
      id: 8,
    },
    {
      province: "یزد",
      value: "بافق",
      label: "بافق",
      id: 2,
    },
    {
      province: "یزد",
      value: "بهاباد",
      label: "بهاباد",
      id: 11,
    },
    {
      province: "یزد",
      value: "تفت",
      label: "تفت",
      id: 3,
    },
    {
      province: "یزد",
      value: "خاتم",
      label: "خاتم",
      id: 9,
    },
    {
      province: "یزد",
      value: "زارچ",
      label: "زارچ",
      id: 13,
    },
    {
      province: "یزد",
      value: "مروست",
      label: "مروست",
      id: 12,
    },
    {
      province: "یزد",
      value: "مهريز",
      label: "مهريز",
      id: 4,
    },
    {
      province: "یزد",
      value: "ميبد",
      label: "ميبد",
      id: 6,
    },
    {
      province: "یزد",
      value: "یزد",
      label: "یزد",
      id: 5,
    },
    {
      province: "هرمزگان",
      value: "ابوموسي",
      label: "ابوموسي",
      id: 1,
    },
    {
      province: "هرمزگان",
      value: "بستك",
      label: "بستك",
      id: 9,
    },
    {
      province: "هرمزگان",
      value: "بشاگرد",
      label: "بشاگرد",
      id: 13,
    },
    {
      province: "هرمزگان",
      value: "بندرعباس",
      label: "بندرعباس",
      id: 2,
    },
    {
      province: "هرمزگان",
      value: "بندرلنگه",
      label: "بندرلنگه",
      id: 3,
    },
    {
      province: "هرمزگان",
      value: "جاسك",
      label: "جاسك",
      id: 6,
    },
    {
      province: "هرمزگان",
      value: "حاجي اباد",
      label: "حاجي اباد",
      id: 8,
    },
    {
      province: "هرمزگان",
      value: "خمير",
      label: "خمير",
      id: 10,
    },
    {
      province: "هرمزگان",
      value: "رودان",
      label: "رودان",
      id: 7,
    },
    {
      province: "هرمزگان",
      value: "سيريك",
      label: "سيريك",
      id: 12,
    },
    {
      province: "هرمزگان",
      value: "قشم",
      label: "قشم",
      id: 4,
    },
    {
      province: "هرمزگان",
      value: "ميناب",
      label: "ميناب",
      id: 5,
    },
    {
      province: "هرمزگان",
      value: "پارسيان",
      label: "پارسيان",
      id: 11,
    },
    {
      province: "تهران",
      value: "اسلامشهر",
      label: "اسلامشهر",
      id: 10,
    },
    {
      province: "تهران",
      value: "بهارستان",
      label: "بهارستان",
      id: 19,
    },
    {
      province: "تهران",
      value: "تهران",
      label: "تهران",
      id: 1,
    },
    {
      province: "تهران",
      value: "دماوند",
      label: "دماوند",
      id: 2,
    },
    {
      province: "تهران",
      value: "رئ",
      label: "رئ",
      id: 3,
    },
    {
      province: "تهران",
      value: "رباط کريم",
      label: "رباط کريم",
      id: 12,
    },
    {
      province: "تهران",
      value: "شميرانات",
      label: "شميرانات",
      id: 4,
    },
    {
      province: "تهران",
      value: "شهريار",
      label: "شهريار",
      id: 9,
    },
    {
      province: "تهران",
      value: "فيروزكوه",
      label: "فيروزكوه",
      id: 14,
    },
    {
      province: "تهران",
      value: "قدس",
      label: "قدس",
      id: 16,
    },
    {
      province: "تهران",
      value: "قرچک",
      label: "قرچک",
      id: 21,
    },
    {
      province: "تهران",
      value: "ملارد",
      label: "ملارد",
      id: 17,
    },
    {
      province: "تهران",
      value: "ورامين",
      label: "ورامين",
      id: 6,
    },
    {
      province: "تهران",
      value: "پاكدشت",
      label: "پاكدشت",
      id: 13,
    },
    {
      province: "تهران",
      value: "پرديس",
      label: "پرديس",
      id: 20,
    },
    {
      province: "تهران",
      value: "پيشوا",
      label: "پيشوا",
      id: 18,
    },
    {
      province: "اردبیل",
      value: "اردبیل",
      label: "اردبیل",
      id: 1,
    },
    {
      province: "اردبیل",
      value: "اصلاندوز",
      label: "اصلاندوز",
      id: 11,
    },
    {
      province: "اردبیل",
      value: "انگوت",
      label: "انگوت",
      id: 12,
    },
    {
      province: "اردبیل",
      value: "بيله سوار",
      label: "بيله سوار",
      id: 2,
    },
    {
      province: "اردبیل",
      value: "خلخال",
      label: "خلخال",
      id: 3,
    },
    {
      province: "اردبیل",
      value: "سرعين",
      label: "سرعين",
      id: 10,
    },
    {
      province: "اردبیل",
      value: "كوثر",
      label: "كوثر",
      id: 7,
    },
    {
      province: "اردبیل",
      value: "مشگين شهر",
      label: "مشگين شهر",
      id: 4,
    },
    {
      province: "اردبیل",
      value: "نمين",
      label: "نمين",
      id: 8,
    },
    {
      province: "اردبیل",
      value: "نير",
      label: "نير",
      id: 9,
    },
    {
      province: "اردبیل",
      value: "پارس آباد",
      label: "پارس آباد",
      id: 6,
    },
    {
      province: "اردبیل",
      value: "گرمي",
      label: "گرمي",
      id: 5,
    },
    {
      province: "قم",
      value: "جعفرآباد",
      label: "جعفرآباد",
      id: 2,
    },
    {
      province: "قم",
      value: "قم",
      label: "قم",
      id: 1,
    },
    {
      province: "قم",
      value: "کهک",
      label: "کهک",
      id: 3,
    },
    {
      province: "قزوین",
      value: "آبيك",
      label: "آبيك",
      id: 4,
    },
    {
      province: "قزوین",
      value: "آوج",
      label: "آوج",
      id: 6,
    },
    {
      province: "قزوین",
      value: "البرز",
      label: "البرز",
      id: 5,
    },
    {
      province: "قزوین",
      value: "بوئين زهرا",
      label: "بوئين زهرا",
      id: 1,
    },
    {
      province: "قزوین",
      value: "تاكستان",
      label: "تاكستان",
      id: 2,
    },
    {
      province: "قزوین",
      value: "قزوین",
      label: "قزوین",
      id: 3,
    },
    {
      province: "گلستان",
      value: "آزادشهر",
      label: "آزادشهر",
      id: 10,
    },
    {
      province: "گلستان",
      value: "آق قلا",
      label: "آق قلا",
      id: 8,
    },
    {
      province: "گلستان",
      value: "بندرگز",
      label: "بندرگز",
      id: 1,
    },
    {
      province: "گلستان",
      value: "تركمن",
      label: "تركمن",
      id: 2,
    },
    {
      province: "گلستان",
      value: "راميان",
      label: "راميان",
      id: 11,
    },
    {
      province: "گلستان",
      value: "علي آباد کتول",
      label: "علي آباد کتول",
      id: 3,
    },
    {
      province: "گلستان",
      value: "كردكوئ",
      label: "كردكوئ",
      id: 4,
    },
    {
      province: "گلستان",
      value: "كلاله",
      label: "كلاله",
      id: 9,
    },
    {
      province: "گلستان",
      value: "مراوه تپه",
      label: "مراوه تپه",
      id: 12,
    },
    {
      province: "گلستان",
      value: "مينودشت",
      label: "مينودشت",
      id: 7,
    },
    {
      province: "گلستان",
      value: "گاليكش",
      label: "گاليكش",
      id: 14,
    },
    {
      province: "گلستان",
      value: "گرگان",
      label: "گرگان",
      id: 5,
    },
    {
      province: "گلستان",
      value: "گميشان",
      label: "گميشان",
      id: 13,
    },
    {
      province: "گلستان",
      value: "گنبدكاووس",
      label: "گنبدكاووس",
      id: 6,
    },
    {
      province: "خراسان شمالی",
      value: "اسفراين",
      label: "اسفراين",
      id: 1,
    },
    {
      province: "خراسان شمالی",
      value: "بجنورد",
      label: "بجنورد",
      id: 2,
    },
    {
      province: "خراسان شمالی",
      value: "جاجرم",
      label: "جاجرم",
      id: 3,
    },
    {
      province: "خراسان شمالی",
      value: "راز و جرگلان",
      label: "راز و جرگلان",
      id: 8,
    },
    {
      province: "خراسان شمالی",
      value: "شيروان",
      label: "شيروان",
      id: 4,
    },
    {
      province: "خراسان شمالی",
      value: "فاروج",
      label: "فاروج",
      id: 5,
    },
    {
      province: "خراسان شمالی",
      value: "مانه وسملقان",
      label: "مانه وسملقان",
      id: 6,
    },
    {
      province: "خراسان شمالی",
      value: "گرمه",
      label: "گرمه",
      id: 7,
    },
    {
      province: "خراسان جنوبی",
      value: "بشرويه",
      label: "بشرويه",
      id: 8,
    },
    {
      province: "خراسان جنوبی",
      value: "بيرجند",
      label: "بيرجند",
      id: 1,
    },
    {
      province: "خراسان جنوبی",
      value: "خوسف",
      label: "خوسف",
      id: 10,
    },
    {
      province: "خراسان جنوبی",
      value: "درميان",
      label: "درميان",
      id: 2,
    },
    {
      province: "خراسان جنوبی",
      value: "زيرکوه",
      label: "زيرکوه",
      id: 9,
    },
    {
      province: "خراسان جنوبی",
      value: "سرايان",
      label: "سرايان",
      id: 6,
    },
    {
      province: "خراسان جنوبی",
      value: "سربيشه",
      label: "سربيشه",
      id: 3,
    },
    {
      province: "خراسان جنوبی",
      value: "طبس",
      label: "طبس",
      id: 11,
    },
    {
      province: "خراسان جنوبی",
      value: "فردوس",
      label: "فردوس",
      id: 7,
    },
    {
      province: "خراسان جنوبی",
      value: "قائنات",
      label: "قائنات",
      id: 4,
    },
    {
      province: "خراسان جنوبی",
      value: "نهبندان",
      label: "نهبندان",
      id: 5,
    },
    {
      province: "البرز",
      value: "اشتهارد",
      label: "اشتهارد",
      id: 5,
    },
    {
      province: "البرز",
      value: "ساوجبلاغ",
      label: "ساوجبلاغ",
      id: 2,
    },
    {
      province: "البرز",
      value: "طالقان",
      label: "طالقان",
      id: 4,
    },
    {
      province: "البرز",
      value: "فرديس",
      label: "فرديس",
      id: 6,
    },
    {
      province: "البرز",
      value: "نظرآباد",
      label: "نظرآباد",
      id: 3,
    },
    {
      province: "البرز",
      value: "چهارباغ",
      label: "چهارباغ",
      id: 7,
    },
    {
      province: "البرز",
      value: "کرج",
      label: "کرج",
      id: 1,
    },
  ];
  