export const provinces = [
    { id: "azerbaijan-east", name: "آذربایجان شرقی" },
    { id: "azerbaijan-west", name: "آذربایجان غربی" },
    { id: "ardabil", name: "اردبیل" },
    { id: "isfahan", name: "اصفهان" },
    { id: "alborz", name: "البرز" },
    { id: "ilam", name: "ایلام" },
    { id: "bushehr", name: "بوشهر" },
    { id: "tehran", name: "تهران" },
    { id: "chahar-mahaal-bakhtiari", name: "چهارمحال بختیاری" },
    { id: "khorasan-south", name: "خراسان جنوبی" },
    { id: "khorasan-razavi", name: "خراسان رضوی" },
    { id: "khorasan-north", name: "خراسان شمالی" },
    { id: "khuzestan", name: "خوزستان" },
    { id: "zanjan", name: "زنجان" },
    { id: "semnan", name: "سمنان" },
    { id: "sistan-baluchestan", name: "سیستان و بلوچستان" },
    { id: "fars", name: "فارس" },
    { id: "qazvin", name: "قزوین" },
    { id: "qom", name: "قم" },
    { id: "kurdistan", name: "کردستان" },
    { id: "kerman", name: "کرمان" },
    { id: "kermanshah", name: "کرمانشاه" },
    { id: "kohgiluyeh-boyer-ahmad", name: "کهگیلویه و بویر احمد" },
    { id: "golestan", name: "گلستان" },
    { id: "gilan", name: "گیلان" },
    { id: "lorestan", name: "لرستان" },
    { id: "mazandaran", name: "مازندران" },
    { id: "markazi", name: "مرکزی" },
    { id: "hormozgan", name: "هرمزگان" },
    { id: "hamadan", name: "همدان" },
    { id: "yazd", name: "یزد" }
  ];
  